CREATE TABLE IF NOT EXISTS public."patientGenInfo"
(
    patient_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    fname character varying(64) COLLATE pg_catalog."default",
    lname character varying(64) COLLATE pg_catalog."default",
    sex character varying(64) COLLATE pg_catalog."default",
    age character varying(64) COLLATE pg_catalog."default",
    insurance character varying(64) COLLATE pg_catalog."default",
    pcp character varying(64) COLLATE pg_catalog."default",
    birth_year integer,
    birth_day integer,
    birth_month character varying(10) COLLATE pg_catalog."default",
    soc_hist_occ character varying(40) COLLATE pg_catalog."default",
    soc_hist_diet character varying(40) COLLATE pg_catalog."default",
    soc_hist_exc character varying(40) COLLATE pg_catalog."default",
    marijuana_use character varying(40) COLLATE pg_catalog."default",
    fun_drugs character varying(40) COLLATE pg_catalog."default",
    desire_to_quit character varying(10) COLLATE pg_catalog."default",
    caffeine_use character varying(25) COLLATE pg_catalog."default",
    alc_use character varying(40) COLLATE pg_catalog."default",
    sex_active character varying(40) COLLATE pg_catalog."default",
    last_year_part character varying(40) COLLATE pg_catalog."default",
    protection_use character varying(40) COLLATE pg_catalog."default",
    sti character varying(40) COLLATE pg_catalog."default",
    curr_housing character varying(40) COLLATE pg_catalog."default",
    yr3_housing character varying(40) COLLATE pg_catalog."default",
    fam_mother character varying(40) COLLATE pg_catalog."default",
    fam_father character varying(40) COLLATE pg_catalog."default",
    fam_siblings character varying(40) COLLATE pg_catalog."default",
    fam_children character varying(40) COLLATE pg_catalog."default",
    fam_sig_other character varying(40) COLLATE pg_catalog."default",
    packs_day integer,
    tobac_yrs integer,
    pack_yrs integer,
    birthday character varying(64) COLLATE pg_catalog."default",
    pets character varying(40) COLLATE pg_catalog."default",
    CONSTRAINT "patientGenInfo_pkey" PRIMARY KEY (patient_id)
)